# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("Tokenize"); Pkg.test("Tokenize"; coverage=true)'
  - julia -e 'Pkg.clone("https://github.com/ZacLN/CSTParser.jl"); Pkg.test("CSTParser")'
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("Tokenize")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("Tokenize")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
